import { Song } from '@/types';

// Tracks sourced from verified Spotify albums and playlists:
//   Matan Ariel – Hanukkah Songs      2h0bRlNupXVXDyIxSQ9aXE
//   Matan Ariel – Purim Songs         4N8JMzGJG6iALwRCagzHTP
//   Matan Ariel – Passover Songs      6O6TJeODOF9jC73xgCRl8x
//   Matan Ariel – Shabbat Songs       77o7nN2MNtQgfbL0WPdclT
//   Matan Ariel – New Year / Sukkot   5Y9dI0gUIJ0SHS9kejn18D
//   Matan Ariel – Travel in Israel    1a1Ii6d4a2PX9i2bABviu4
//   Matan Ariel – Summer & Winter     0oz9zR0Llscfnz03Nuk5dC
//   Hop! Channel – שירים לקטנטנים    5EqXBvTWgHRvKS36WYSf7n
//   Playlist – שירי חורף לילדים      6CDhX0UcCA3cnFbAydJ3Ex
//   Playlist – שירי אביב ופסח         6hbITTsXXuHOaLBPSMG7nV
//   Playlist – שירי קיץ לילדים        6oV13NZ0NoTO6r4UsSqLMF
//   Playlist – שירי סתיו לילדים       408EpG4pHAFEXNLF0pXYqc
//   Playlist – ט"ו בשבט שירי ילדים   3Y3WrG1LrFFMHuIFWCWHiK
//   Playlist – שירי שבועות לילדים     5gtO3OrrKCnkS37hyKVEyY
//   Playlist – יום העצמאות שירי ילדים 4AYjMHYehU6g1bTVFtCWOk

export const ALL_SONGS: Song[] = [

  // ── HANUKKAH (winter) ─────────────────────────────────────────────────────
  {
    id: 'sevivon',
    titleHe: 'סְבִיבוֹן סוֹב סוֹב סוֹב',
    titleTranslit: 'Sevivon, Sov Sov Sov',
    spotifyTrackId: '2cZjmCYzsdqr5D7vHSIpI5',
    tags: ['hanukkah', 'season-winter'],
    emoji: '🕎',
  },
  {
    id: 'banu-choshech',
    titleHe: 'בָּאנוּ חוֹשֶׁךְ לְגָרֵשׁ',
    titleTranslit: "Banu Choshech L'garesh",
    spotifyTrackId: '1zD0ePmN78PNwCfOg1lmxX',
    tags: ['hanukkah', 'season-winter'],
    emoji: '🕯️',
  },
  {
    id: 'ner-li',
    titleHe: 'נֵר לִי נֵר לִי',
    titleTranslit: 'Ner Li Ner Li',
    spotifyTrackId: '24TlMayZKFxJnBeYtdOk5h',
    tags: ['hanukkah', 'season-winter'],
    emoji: '🌟',
  },
  {
    id: 'mi-yimalel',
    titleHe: 'מִי יְמַלֵּל',
    titleTranslit: 'Mi Yimalel',
    spotifyTrackId: '29bV3bP119sxn1suCYWZ9N',
    tags: ['hanukkah', 'season-winter'],
    emoji: '💪',
  },
  {
    id: 'yemei-hahanukkah',
    titleHe: 'יְמֵי הַחֲנֻכָּה',
    titleTranslit: 'Yemei HaHanukkah',
    spotifyTrackId: '6efzq6Mzr38CNDCgajRZ4b',
    tags: ['hanukkah', 'season-winter'],
    emoji: '🎉',
  },
  {
    id: 'maoz-tzur',
    titleHe: 'מָעוֹז צוּר',
    titleTranslit: 'Maoz Tzur',
    spotifyTrackId: '7vi1CZwPJwpxujJOfns6jv',
    tags: ['hanukkah', 'season-winter'],
    emoji: '🏰',
  },
  {
    id: 'haneirot-halalu',
    titleHe: 'הַנֵּרוֹת הַלָּלוּ',
    titleTranslit: 'HaNeirot Halalu',
    spotifyTrackId: '3mpjWlEvvoZF2w5N5LoEYL',
    tags: ['hanukkah', 'season-winter'],
    emoji: '🕯️',
  },
  {
    id: 'kad-katan',
    titleHe: 'כַּד קָטָן',
    titleTranslit: 'Kad Katan',
    spotifyTrackId: '2iDvB1lmtIr44kPR2guVEf',
    tags: ['hanukkah', 'season-winter'],
    emoji: '🏺',
  },
  {
    id: 'neirot-rabim',
    titleHe: 'נֵרוֹת רַבִּים',
    titleTranslit: 'Neirot Rabim',
    spotifyTrackId: '7K6Yew1jmf3tECAUeKpkob',
    tags: ['hanukkah', 'season-winter'],
    emoji: '✨',
  },

  // ── PURIM (spring) ────────────────────────────────────────────────────────
  {
    id: 'chag-purim',
    titleHe: 'חַג פּוּרִים',
    titleTranslit: 'Chag Purim',
    spotifyTrackId: '6Y9m8opaAuCljlvUGz4JNf',
    tags: ['purim', 'season-spring'],
    emoji: '🎭',
  },
  {
    id: 'ani-purim',
    titleHe: 'אֲנִי פּוּרִים',
    titleTranslit: 'Ani Purim',
    spotifyTrackId: '32aXBd19TIZT67i90uk9ui',
    tags: ['purim', 'season-spring'],
    emoji: '🥳',
  },
  {
    id: 'shoshanat-yaakov',
    titleHe: 'שׁוֹשַׁנַּת יַעֲקֹב',
    titleTranslit: 'Shoshanat Yaakov',
    spotifyTrackId: '6Ymee8s1OPXa66817zM1JC',
    tags: ['purim', 'season-spring'],
    emoji: '🌹',
  },
  {
    id: 'mishenichnas-adar',
    titleHe: 'מִשֶּׁנִּכְנַס אֲדָר',
    titleTranslit: 'Mishenichnas Adar',
    spotifyTrackId: '0rlnIEfppXl1POosolezBx',
    tags: ['purim', 'season-spring'],
    emoji: '🎊',
  },
  {
    id: 'leitzan-katan',
    titleHe: 'לֵיצָן קָטָן',
    titleTranslit: 'Leitzan Katan',
    spotifyTrackId: '0YjEIotcRx646ubYM7XsV4',
    tags: ['purim', 'season-spring'],
    emoji: '🤡',
  },
  {
    id: 'hayom-purim',
    titleHe: 'הַיּוֹם פּוּרִים',
    titleTranslit: 'HaYom Purim',
    spotifyTrackId: '30HwR1azzBqDMPCnnrtzyK',
    tags: ['purim', 'season-spring'],
    emoji: '🎈',
  },
  {
    id: 'venahafoch-hu',
    titleHe: 'וְנַהֲפוֹךְ הוּא',
    titleTranslit: 'VeNahafoch Hu',
    spotifyTrackId: '2DNzz9kbTMZK1x5FWZEYeu',
    tags: ['purim', 'season-spring'],
    emoji: '🔄',
  },

  // ── PESACH (spring) ───────────────────────────────────────────────────────
  {
    id: 'dayenu',
    titleHe: 'דַּיֵּנוּ',
    titleTranslit: 'Dayenu',
    spotifyTrackId: '7p7OJJUVFzIza4h3cQBs5T',
    tags: ['pesach', 'season-spring'],
    emoji: '🫓',
  },
  {
    id: 'chad-gadya',
    titleHe: 'חַד גַּדְיָא',
    titleTranslit: 'Chad Gadya',
    spotifyTrackId: '0878W8DunIhyMyEQQhnye6',
    tags: ['pesach', 'season-spring'],
    emoji: '🐐',
  },
  {
    id: 'ma-nishtana',
    titleHe: 'מַה נִּשְׁתַּנָּה',
    titleTranslit: 'Ma Nishtana',
    spotifyTrackId: '47IOKYtlPuZzDegBHr8FjL',
    tags: ['pesach', 'season-spring'],
    emoji: '❓',
  },
  {
    id: 'avadim-hayinu',
    titleHe: 'עֲבָדִים הָיִינוּ',
    titleTranslit: 'Avadim Hayinu',
    spotifyTrackId: '680CqvCriY7nqUHz6pPTiX',
    tags: ['pesach', 'season-spring'],
    emoji: '🗝️',
  },
  {
    id: 'echad-mi-yodea',
    titleHe: 'אֶחָד מִי יוֹדֵעַ',
    titleTranslit: 'Echad Mi Yodea',
    spotifyTrackId: '2Np0jDaS73OyLf8iFhHIiq',
    tags: ['pesach', 'season-spring'],
    emoji: '🔢',
  },
  {
    id: 'eliyahu-hanavi',
    titleHe: 'אֵלִיָּהוּ הַנָּבִיא',
    titleTranslit: 'Eliyahu HaNavi',
    spotifyTrackId: '210GhYNmEREOBUwQNr8wev',
    tags: ['pesach', 'season-spring'],
    emoji: '🍷',
  },
  {
    id: 'moshe-bateva',
    titleHe: 'מֹשֶׁה בַּתֵּבָה',
    titleTranslit: 'Moshe BaTeva',
    spotifyTrackId: '3ZE6yqScHqmX6ZhodZKk2b',
    tags: ['pesach', 'season-spring'],
    emoji: '⛵',
  },

  // ── SHABBAT ───────────────────────────────────────────────────────────────
  {
    id: 'shalom-aleichem',
    titleHe: 'שָׁלוֹם עֲלֵיכֶם',
    titleTranslit: 'Shalom Aleichem',
    spotifyTrackId: '19ocz54yXGYvKW8cHKTvlw',
    tags: ['shabbat'],
    emoji: '✨',
  },
  {
    id: 'shabbat-shalom',
    titleHe: 'שַׁבָּת שָׁלוֹם',
    titleTranslit: 'Shabbat Shalom',
    spotifyTrackId: '1kFCUclAFnFDH8YIIeooSo',
    tags: ['shabbat'],
    emoji: '🕯️',
  },
  {
    id: 'lecha-dodi',
    titleHe: 'לְכָה דוֹדִי',
    titleTranslit: 'Lecha Dodi',
    spotifyTrackId: '3uqtUvnPpuUsJ2fLRBdcLS',
    tags: ['shabbat'],
    emoji: '🌙',
  },
  {
    id: 'mi-ohev-shabbat',
    titleHe: 'מִי אוֹהֵב שַׁבָּת',
    titleTranslit: 'Mi Ohev Shabbat',
    spotifyTrackId: '2QqRIOT9LCvnMCywfCtpiG',
    tags: ['shabbat'],
    emoji: '💛',
  },
  {
    id: 'shabbat-hamalka',
    titleHe: 'שַׁבָּת הַמַּלְכָּה',
    titleTranslit: 'Shabbat HaMalka',
    spotifyTrackId: '2uBnNuNYRb0rMRLQunvXEM',
    tags: ['shabbat'],
    emoji: '👑',
  },
  {
    id: 'hayom-yom-shishi',
    titleHe: 'הַיּוֹם יוֹם שִׁישִׁי',
    titleTranslit: 'HaYom Yom Shishi',
    spotifyTrackId: '1zUTtlDF9K13TmcibkGH23',
    tags: ['shabbat'],
    emoji: '📅',
  },
  {
    id: 'havdalah',
    titleHe: 'נֵר וּבְשָׂמִים',
    titleTranslit: 'Ner U\'Vsamim',
    spotifyTrackId: '6l3YOUPzewECYiJTDNZv5R',
    tags: ['shabbat'],
    emoji: '🌿',
  },
  {
    id: 'am-yisrael-chai',
    titleHe: 'עַם יִשְׂרָאֵל חַי',
    titleTranslit: 'Am Yisrael Chai',
    spotifyTrackId: '6Eukip0OFIfhptmEiMVKD6',
    tags: ['shabbat', 'yom-haatzmaut', 'general'],
    emoji: '🌟',
  },
  {
    id: 'bim-bam',
    titleHe: 'בִּים בָּם בּוֹם',
    titleTranslit: 'Bim Bam Bom',
    spotifyTrackId: '5zyQMFULXLKDlPIbHR46BA',
    tags: ['shabbat'],
    emoji: '🎶',
  },

  // ── ROSH HASHANA (autumn) ─────────────────────────────────────────────────
  {
    id: 'leshana-tova',
    titleHe: 'לְשָׁנָה טוֹבָה',
    titleTranslit: 'LeShana Tova',
    spotifyTrackId: '6Peone9HtlyRDH2wpVdd5s',
    tags: ['rosh-hashana', 'season-autumn'],
    emoji: '🍎',
  },
  {
    id: 'shana-tova-umetuka',
    titleHe: 'שָׁנָה טוֹבָה וּמְתוּקָה',
    titleTranslit: "Shana Tova U'metuka",
    spotifyTrackId: '1mWFT2vxOzcQ0EgK4GpZJN',
    tags: ['rosh-hashana', 'season-autumn'],
    emoji: '🍯',
  },
  {
    id: 'tsaddik-katamar',
    titleHe: 'צַדִּיק כַּתָּמָר',
    titleTranslit: 'Tzaddik KaTamar',
    spotifyTrackId: '2J605rkSHmVE1skOMNk0PL',
    tags: ['rosh-hashana', 'season-autumn'],
    emoji: '🌴',
  },
  {
    id: 'berosh-hashana',
    titleHe: 'בְּרֹאשׁ הַשָּׁנָה',
    titleTranslit: "B'Rosh HaShana",
    spotifyTrackId: '4J8X9RuIzUSW0Umpa8PQNU',
    tags: ['rosh-hashana', 'season-autumn'],
    emoji: '📯',
  },
  {
    id: 'basshana-habaa',
    titleHe: 'בַּשָּׁנָה הַבָּאָה',
    titleTranslit: "BaSshana HaBa'a",
    spotifyTrackId: '57ZTeUZLWlm9TdCC2XKDb1',
    tags: ['rosh-hashana', 'season-autumn'],
    emoji: '🌈',
  },

  // ── SUKKOT (autumn) ───────────────────────────────────────────────────────
  {
    id: 'sukkah-yafa',
    titleHe: 'סֻכָּה יָפָה',
    titleTranslit: 'Sukkah Yafa',
    spotifyTrackId: '1Rb87s6chjQ6KrVfY8vVdY',
    tags: ['sukkot', 'season-autumn'],
    emoji: '🌿',
  },
  {
    id: 'ushpizin',
    titleHe: 'אֻשְׁפִּיזִין',
    titleTranslit: 'Ushpizin',
    spotifyTrackId: '3vJoPRKr4I1cWZClkFnaNq',
    tags: ['sukkot', 'season-autumn'],
    emoji: '🏕️',
  },
  {
    id: 'arba-minim',
    titleHe: 'אַרְבַּעַת הַמִּינִים',
    titleTranslit: "Arba'at HaMinim",
    spotifyTrackId: '7KtBFp1zRBVUSegaimThgz',
    tags: ['sukkot', 'season-autumn'],
    emoji: '🌾',
  },
  {
    id: 'bniyat-sukkah',
    titleHe: 'בּוֹנִים סֻכָּה',
    titleTranslit: 'Bonim Sukkah',
    spotifyTrackId: '4Phlhg3re7UJmRPRqqcc3l',
    tags: ['sukkot', 'season-autumn'],
    emoji: '🔨',
  },
  {
    id: 'hag-haasif',
    titleHe: 'חַג הָאָסִיף',
    titleTranslit: 'Hag HaAsif',
    spotifyTrackId: '2NBMj76KAkYDBHQ3vi3y3V',
    tags: ['sukkot', 'season-autumn'],
    emoji: '🌽',
  },

  // ── TU BISHVAT (late winter / early spring) ───────────────────────────────
  {
    id: 'hashkediya',
    titleHe: 'הַשְּׁקֵדִיָּה פּוֹרַחַת',
    titleTranslit: 'HaShkediya Porachat',
    spotifyTrackId: '1GOeHJ72PND3XDVfQpICKG',
    tags: ['tu-bishvat', 'season-spring', 'season-winter'],
    emoji: '🌸',
  },
  {
    id: 'tu-bishvat',
    titleHe: 'טוּ בִּשְׁבָט',
    titleTranslit: "Tu BiShvat",
    spotifyTrackId: '2rc4VhQ531DE50FtBsVSQZ',
    tags: ['tu-bishvat', 'season-winter'],
    emoji: '🌳',
  },
  {
    id: 'ma-osim-haetzim',
    titleHe: 'מָה עוֹשִׂים הָעֵצִים',
    titleTranslit: 'Ma Osim HaEtzim',
    spotifyTrackId: '15UpXUGYKItgEsbMfMHUWE',
    tags: ['tu-bishvat', 'season-winter'],
    emoji: '🌲',
  },
  {
    id: 'etz-natati',
    titleHe: 'עֵץ נָטַעְתִּי',
    titleTranslit: "Etz Nata'ti",
    spotifyTrackId: '3QmCSvoIMU2utUYHmyYgTt',
    tags: ['tu-bishvat', 'season-winter'],
    emoji: '🌱',
  },

  // ── SHAVUOT (spring / early summer) ──────────────────────────────────────
  {
    id: 'bikkurim',
    titleHe: 'בִּכּוּרִים',
    titleTranslit: 'Bikkurim',
    spotifyTrackId: '3mjQB8onh5aMUWMT0kYCKd',
    tags: ['shavuot', 'season-spring'],
    emoji: '🌾',
  },
  {
    id: 'eretz-zavat-chalav',
    titleHe: 'אֶרֶץ זָבַת חָלָב',
    titleTranslit: 'Eretz Zavat Chalav',
    spotifyTrackId: '0Wl25RFZoUrBqEWYwUkuuJ',
    tags: ['shavuot', 'season-spring'],
    emoji: '🥛',
  },
  {
    id: 'salenu',
    titleHe: 'סַלֵּינוּ עַל כְּתֵפֵינוּ',
    titleTranslit: 'Salenu Al Ktafenu',
    spotifyTrackId: '6zMhPsByEv5PvHbGlyZtky',
    tags: ['shavuot', 'season-spring'],
    emoji: '🧺',
  },
  {
    id: 'shibbolet-basadeh',
    titleHe: 'שִׁבֹּלֶת בַּשָּׂדֶה',
    titleTranslit: 'Shibbolet BaSadeh',
    spotifyTrackId: '65WlnCd052jBXckYBti4Nl',
    tags: ['shavuot', 'season-spring'],
    emoji: '🌿',
  },

  // ── YOM HA'ATZMAUT (spring) ───────────────────────────────────────────────
  {
    id: 'eretz-yisrael',
    titleHe: 'אֶרֶץ יִשְׂרָאֵל',
    titleTranslit: 'Eretz Yisrael',
    spotifyTrackId: '1WIHe5GQ5cxy1NRMR5MJ2L',
    tags: ['yom-haatzmaut', 'season-spring'],
    emoji: '🇮🇱',
  },
  {
    id: 'eretz-yisrael-sheli',
    titleHe: 'אֶרֶץ יִשְׂרָאֵל שֶׁלִּי',
    titleTranslit: 'Eretz Yisrael Sheli',
    spotifyTrackId: '58gjKhdAyYFvtuw0sGn95e',
    tags: ['yom-haatzmaut', 'season-spring'],
    emoji: '💙',
  },
  {
    id: 'yerushalayim-shel-zahav',
    titleHe: 'יְרוּשָׁלַיִם שֶׁל זָהָב',
    titleTranslit: 'Yerushalayim Shel Zahav',
    spotifyTrackId: '3PxsXmJuDBD8opYh0njUTy',
    tags: ['yom-haatzmaut', 'season-spring'],
    emoji: '🏙️',
  },
  {
    id: 'hadegel-sheli',
    titleHe: 'הַדֶּגֶל שֶׁלִּי',
    titleTranslit: 'HaDegel Sheli',
    spotifyTrackId: '4CY9iSQ8Nimd7NJ4SyBIAa',
    tags: ['yom-haatzmaut', 'season-spring'],
    emoji: '🚩',
  },
  {
    id: 'kol-haaretz-degalim',
    titleHe: 'כָּל הָאָרֶץ דְּגָלִים',
    titleTranslit: 'Kol HaAretz Degalim',
    spotifyTrackId: '2gJrvemTf7CBI49Bfvy3mo',
    tags: ['yom-haatzmaut', 'season-spring'],
    emoji: '🎌',
  },

  // ── SEASON: WINTER ────────────────────────────────────────────────────────
  {
    id: 'geshem-min-hashamayim',
    titleHe: 'גֶּשֶׁם מִן הַשָּׁמַיִם',
    titleTranslit: 'Geshem Min HaShamayim',
    spotifyTrackId: '25hLWj4WQPLemygwCcjGXv',
    tags: ['season-winter'],
    emoji: '🌧️',
  },
  {
    id: 'geshem-beito',
    titleHe: 'גֶּשֶׁם בְּעִתּוֹ',
    titleTranslit: "Geshem B'Ito",
    spotifyTrackId: '1rfHH3UVbzO7njpGTcn8E5',
    tags: ['season-winter'],
    emoji: '☔',
  },
  {
    id: 'choref',
    titleHe: 'חוֹרֶף',
    titleTranslit: 'Choref',
    spotifyTrackId: '7vpONUPgPDkj4XCl11CwnS',
    tags: ['season-winter'],
    emoji: '❄️',
  },
  {
    id: 'geshem-bo',
    titleHe: 'גֶּשֶׁם בּוֹא',
    titleTranslit: 'Geshem Bo',
    spotifyTrackId: '2tsrc34zQtak5HfWriWTOP',
    tags: ['season-winter'],
    emoji: '🌂',
  },
  {
    id: 'sheleg-al-iri',
    titleHe: 'שֶׁלֶג עַל עִירִי',
    titleTranslit: 'Sheleg Al Iri',
    spotifyTrackId: '2e9tgLBuaQrzs2x3Cc9vIM',
    tags: ['season-winter'],
    emoji: '⛄',
  },

  // ── SEASON: SPRING ────────────────────────────────────────────────────────
  {
    id: 'aviv',
    titleHe: 'אָבִיב',
    titleTranslit: 'Aviv',
    spotifyTrackId: '1O9dDjQLXBi70lrjHERPSz',
    tags: ['season-spring'],
    emoji: '🌷',
  },
  {
    id: 'nitzanim',
    titleHe: 'נִצָּנִים נִרְאוּ בָּאָרֶץ',
    titleTranslit: "Nitzanim Niru Ba'aretz",
    spotifyTrackId: '1PZBqXQWcUn2ePk6fTUS08',
    tags: ['season-spring', 'pesach'],
    emoji: '🌼',
  },
  {
    id: 'hadvora-hacharutza',
    titleHe: 'הַדְּבוֹרָה הַחֲרוּצָה',
    titleTranslit: 'HaDvora HaCharutza',
    spotifyTrackId: '4G6vg8r7xJKHJhA2bBEqcc',
    tags: ['season-spring'],
    emoji: '🐝',
  },
  {
    id: 'haperach-laparpar',
    titleHe: 'הַפֶּרַח לַפַּרְפַּר',
    titleTranslit: 'HaPerach LaParpar',
    spotifyTrackId: '3Ob9eg05WtibSXdLqA8YxL',
    tags: ['season-spring'],
    emoji: '🦋',
  },

  // ── SEASON: SUMMER ────────────────────────────────────────────────────────
  {
    id: 'bakayitz',
    titleHe: 'בַּקַּיִץ',
    titleTranslit: 'BaKayitz',
    spotifyTrackId: '6wYOfPhnfDBiSEylmxzdaN',
    tags: ['season-summer'],
    emoji: '☀️',
  },
  {
    id: 'hachofesh-hagadol',
    titleHe: 'הַחֹפֶשׁ הַגָּדוֹל',
    titleTranslit: 'HaChofesh HaGadol',
    spotifyTrackId: '5vk35wWI5XJMq3PUzdwhUu',
    tags: ['season-summer'],
    emoji: '🏖️',
  },
  {
    id: 'shlosha-dagim',
    titleHe: 'שְׁלֹשָׁה דָּגִים',
    titleTranslit: 'Shlosha Dagim',
    spotifyTrackId: '7lmxz5XTqdKE37yDgqIpkm',
    tags: ['season-summer', 'general'],
    emoji: '🐟',
  },
  {
    id: 'avatiach',
    titleHe: 'אֲבַטִּיחַ',
    titleTranslit: 'Avatiach',
    spotifyTrackId: '2roLJBzYbPyk3a4HTYpHvL',
    tags: ['season-summer'],
    emoji: '🍉',
  },
  {
    id: 'galshan',
    titleHe: 'גַּלְשָׁן',
    titleTranslit: 'Galshan',
    spotifyTrackId: '5SLDiJCzKY1SqAn8pCBQWc',
    tags: ['season-summer'],
    emoji: '🏄',
  },

  // ── SEASON: AUTUMN ────────────────────────────────────────────────────────
  {
    id: 'stav',
    titleHe: 'סְתָו',
    titleTranslit: 'Stav',
    spotifyTrackId: '1VBYWyv1jN2uy4uJtR1p4u',
    tags: ['season-autumn'],
    emoji: '🍂',
  },
  {
    id: 'ruach-stav',
    titleHe: 'רוּחַ סְתָו',
    titleTranslit: 'Ruach Stav',
    spotifyTrackId: '7iTBnOiZ6EI44YiWAEuwPh',
    tags: ['season-autumn'],
    emoji: '🌬️',
  },
  {
    id: 'tziporim-nodedot',
    titleHe: 'צִפּוֹרִים נוֹדְדוֹת',
    titleTranslit: 'Tziporim Nodedot',
    spotifyTrackId: '3MDKL9QzsLbYL9CaxvvMKd',
    tags: ['season-autumn'],
    emoji: '🐦',
  },

  // ── GENERAL CHILDREN'S SONGS ──────────────────────────────────────────────
  {
    id: 'dod-moshe',
    titleHe: 'דּוֹד מֹשֶׁה',
    titleTranslit: 'Dod Moshe',
    spotifyTrackId: '02mAvPve4OValfcBwJC79c',
    tags: ['general'],
    emoji: '🐄',
  },
  {
    id: 'akavish-katan',
    titleHe: 'עַכָּבִישׁ קָטָן',
    titleTranslit: 'Akavish Katan',
    spotifyTrackId: '5zUCyAKIWIFwhbGF8naENZ',
    tags: ['general'],
    emoji: '🕷️',
  },
  {
    id: 'nitzantz-kochav',
    titleHe: 'נִצְנֵץ כּוֹכָב',
    titleTranslit: 'Nitzantz Kochav',
    spotifyTrackId: '0eNjEDMqRTJXSskIbgCIXi',
    tags: ['general'],
    emoji: '⭐',
  },
  {
    id: 'yadayim-lemala',
    titleHe: 'יָדַיִם לְמַעְלָה',
    titleTranslit: "Yadayim L'Mala",
    spotifyTrackId: '0JtXb0B2DzOHE7SGOd5pMs',
    tags: ['general'],
    emoji: '🙌',
  },
  {
    id: 'barvazim',
    titleHe: 'בַּרְוָזִים',
    titleTranslit: 'Barvazim',
    spotifyTrackId: '3VhVN2chWHtdlzecpRF9tg',
    tags: ['general'],
    emoji: '🦆',
  },
  {
    id: 'numi-numi',
    titleHe: 'נוּמִי נוּמִי',
    titleTranslit: 'Numi Numi',
    spotifyTrackId: '4XZFwGxtAN9a898BgAjDfI',
    tags: ['general'],
    emoji: '😴',
  },
  {
    id: 'numi-yaldi',
    titleHe: 'נוּמִי יַלְדִּי',
    titleTranslit: 'Numi Yaldi',
    spotifyTrackId: '3umVNoj3ttnM9Oqk77t73H',
    tags: ['general'],
    emoji: '🌙',
  },
  {
    id: 'kol-haolam-kulo',
    titleHe: 'כָּל הָעוֹלָם כֻּלּוֹ',
    titleTranslit: 'Kol HaOlam Kulo',
    spotifyTrackId: '4VppInZBDQNXxfkYvrQGaQ',
    tags: ['general'],
    emoji: '🌍',
  },
  {
    id: 'ani-veata',
    titleHe: 'אֲנִי וְאַתָּה',
    titleTranslit: 'Ani VeAta',
    spotifyTrackId: '2T7SKz1GQOwWG98341SFJT',
    tags: ['general'],
    emoji: '👫',
  },
  {
    id: 'yom-huledet',
    titleHe: 'יוֹם הֻלֶּדֶת שָׂמֵחַ',
    titleTranslit: 'Yom Huledet Sameach',
    spotifyTrackId: '0fYd57xHUBIXtWpGLaSif3',
    tags: ['general'],
    emoji: '🎂',
  },
  {
    id: 'pil-katan',
    titleHe: 'פִּיל קָטָן',
    titleTranslit: 'Pil Katan',
    spotifyTrackId: '4DR7QzgSKcxOfD4ITmnw8A',
    tags: ['general'],
    emoji: '🐘',
  },
  {
    id: 'zebra-pijama',
    titleHe: 'לָמָּה הַזֶּבְּרָה לוֹבֶשֶׁת פִּיגָ׳מָה',
    titleTranslit: 'Lama HaZebra Loveshet Pijama',
    spotifyTrackId: '1Udhxm2cLinbQde7P4awTv',
    tags: ['general'],
    emoji: '🦓',
  },
];
